Added new setup script

diff --git a/setup-401-js b/setup-401-js
--- a/setup-401-js
+++ b/setup-401-js
@@ -1,113 +1,72 @@
 #!/bin/bash
 
-help() {
-    echo
-    echo "Usage: setup-401-js -c class-ode -t target-folder"
-    echo
-    echo "  -c [class-code] (i.e. javascript-401d29)"
-    echo "     required"
-    echo
-    echo "  -t [target-folder] (i.e. ~/codefellows/classes)"
-    echo "     defaults to the current folder"
-    echo
-    echo "  -m -push the class repository to master (all files/folders)"
-    echo "     default - no push"
-    echo
-    echo "Environment Variables Required:"
-    echo "  GIT_USER - Your github login id"
-    echo "  GIT_TOKEN - A Github developer token for the GIT_USER account"
-    echo "              with read access to the codefellows/code-401-javascript-guide reoi"
-    echo
-    echo "This Application will:"
-    echo "  - create a repository named 'seattle-javascript-CLASS-CODE'"
-    echo "  - create a folder named 'CLASS-CODE' in your designated target"
-    echo "  - copy the files/folders from the most up to date js guide repo"
-    echo "  - (optionally) push everything to master"
-    echo
-}
+# USAGE: setup-
+# -c Class Code`
 
-error() {
-    echo -------------------------------------------------------
-    echo ERROR: $1
-    help
-    echo -------------------------------------------------------
-    exit;
-}
-
-setup_class() {
-
-    mkdir -p $CLASS_FOLDER
-
-    cd $CLASS_FOLDER
-
-    curl -L https://github.com/codefellows/code-401-javascript-guide/archive/master.zip -H "Authorization:Bearer $GIT_TOKEN" > 401.zip
-      unzip 401.zip
-      rm -rf 401.zip
-
-    mkdir apps-and-libraries
-    mv code-401-javascript-guide-master/configs .
-    mv code-401-javascript-guide-master/reference .
-    mv code-401-javascript-guide-master/curriculum .
-
-    rm -rf curriculum/data-structures
-    rm -rf curriculum/design-assignments
-    rm -rf curriculum/warm-ups
-    rm -rf code-401-javascript-guide-master
-
-    for i in $( ls -A -d curriculum/class-* );
-      do  rm -rf $i/solution; rm -rf $i/facilitator;
-    done;
-
-    # Setup Github
-    curl -u $GIT_USER:$GIT_TOKEN https://api.github.com/orgs/codefellows/repos -d '{"name":"'$REPO'"}'
-
-    git init
-    git remote add origin git@github.com:codefellows/$REPO.git
-
-    if [ $PUSH_TO_MASTER -eq 1 ]; then
-      git add .
-      git commit -m "Class Repo Initialization"
-      git push origin master
-      echo "Pushed everything to master";
-    fi
-
-}
-
-OK=0;
-PUSH_TO_MASTER=0;
-while getopts :t:c:m option
+while getopts c:r: option
 do
-  case "${option}"
-    in
-      c) OK=1;CLASS=${OPTARG};;
-      t) TARGET=${OPTARG};;
-      m) PUSH_TO_MASTER=1;;
-      h) help;exit;;
-  esac
+case "${option}"
+in
+c) CLASS=${OPTARG};;
+r) CLASS_REPO=${OPTARG};;
+esac
 done
 
-if [ $OK -eq 0 ]; then
-  error "Class Code Required"
+if [ ! "$CLASS" ]; then
+   echo "Class Code Required"
+   exit 2
 fi
 
-if [ -z "$GIT_USER" ]; then
-  error "Missing GIT_USER environment variable"
+if [ ! "$CLASS_REPO" ]; then
+   echo "Class Repository Required"
+   exit 2
 fi
 
-if [ -z "$GIT_TOKEN" ]; then
-  error "Missing GIT_TOKEN environment variable"
-fi
+GUIDE=git@github.com:codefellows/code-401-javascript-guide.git
+GUIDE_NAME=code-401-javascript-guide.git
 
-## Default TARGET to the current folder
-: ${TARGET=.}
+mkdir scratch
+cd scratch || exit
 
-REPO="seattle-javascript-$CLASS"
-CLASS_FOLDER="$TARGET/$CLASS"
+git clone --bare $GUIDE
 
-echo Class Code: $CLASS
-echo Local Repo Folder: $CLASS_FOLDER
-echo Github Repo: $REPO
+cd $GUIDE_NAME || exit
 
-setup_class
+git push --mirror $CLASS_REPO
+
+cd ../..
+rm -rf scratch
 
 
+## Clone the new copy
+git clone $CLASS_REPO ./$CLASS
+
+## Reconfigure .gitignore
+cd $CLASS || exit
+
+## Send up the new .gitignore so we don't push facilitator stuff to the class.
+cat >> .gitignore <<EOL
+# 401JS Guide
+solution
+facilitator
+apps-and-libraries
+extra-content
+setup-401-js
+student-comments.md
+/README.md
+**/demo/README.md
+FACILITATOR.md
+EOL
+
+git add .
+git commit -m "Updated .gitignore"
+git push origin master
+
+## Clear out the repo, and then push it clean (force obey .gitignore)
+git rm -r --cached .
+git add .
+git commit -m "Clear Out the Guide Fluff"
+git push origin master
+
+# Connect to the guide as an upstream
+git remote add upstream $GUIDE
